statementPaths:
  - C:\dev\tst\finrazbl\kl_to_1c.txt
  - C:\dev\tst\finrazbl\kl_to_1c(2).txt
  - C:\dev\tst\finrazbl\kl_to_1c(3).txt
  - C:\dev\tst\finrazbl\kl_to_1c(4).txt
  - C:\dev\tst\finrazbl\kl_to_1c(5).txt
firms:
  - АТМ
  - Аналитприбор
  - Межотраслевой центр экспертиз
  - ПрогрессТехМаш
xlsDirectories:
  - D:\accountant config\2018
  - D:\accountant config\2017
sheetsForThemes:
  - МО+ио
  - аэс
initialFile: C:\dev\tst\finrazbl\2018
settingsFile: C:\tmp\settings.s